name: bangla_ledger_app
description: A simple offline Bangla ledger app with name search, add payments, and simple interest (3% per month).
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/